### ISSUE TITLE
Legion commanders don't show

### ISSUE THREAD

**Issue by Quitch** [speth/planetary-annihilation-db#9]
Legion operates by replacing the Invictus and Aseon commanders with its own. However there's no way to view their stats in pa-db. Showing Commander variants does not display them.

**Comment by speth** [comment]
They're getting filtered out for two related reasons:
1. They don't have a `base_spec` that links back to the 'base_commander' template
2. They don't have a non-zero value for `build_metal_cost` (which they would inherit from `base_commander`)
The first one I have a simple enough fix for, but I'm not entirely sure what to do about the second one, since that's a pretty useful filter for removing crap, especially in some of the earlier builds.

**Comment by Quitch** [comment]
Our mod requires the use of the base_spec, so that's bug to be raised on our end. I'll take care of that.
